"""address_doc.py [out.md] -- docs/ADDRESSES.md from the hand-kept name lists.

Every address the port relies on lives in tools/re/names/make_manual.py, one
list per DLL build; this writes them out readable, per build, grouped by module,
with the build's identity (size, SHA-256, PE timestamp, whether the installed
game still has it) and where src/ cites each address. Rerun after editing
make_manual.py (and after make_manual.py itself has been run).
"""
import datetime
import glob
import hashlib
import json
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
NAMES = os.path.join(HERE, "names")
CS2 = os.environ.get("CS2_DIR", r"D:\Steam\steamapps\common\Counter-Strike Global Offensive")
INSTALLED = {"hammer": os.path.join(CS2, "game", "bin", "win64", "tools", "hammer.dll")}
BUILDS = [r"D:\tools\binaries", r"D:\tools\ghidra_staging"]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def pe_time(path):
    with open(path, "rb") as f:
        head = f.read(4096)
    pe = struct.unpack_from("<I", head, 0x3C)[0]
    stamp = struct.unpack_from("<I", head, pe + 8)[0]
    return datetime.datetime.fromtimestamp(stamp, datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_file(dll, build):
    for d in BUILDS:
        p = os.path.join(d, f"{dll}_{build}.dll")
        if os.path.exists(p):
            return p
    installed = INSTALLED.get(dll, os.path.join(CS2, "game", "bin", "win64", dll + ".dll"))
    return installed if os.path.exists(installed) else None


def patch_verdicts():
    """Per DLL, the tracked-address line of the newest patch_check report."""
    reports = sorted(glob.glob(os.path.join(r"D:\tools\patch_reports", "*.md")), key=os.path.getmtime)
    if not reports:
        return None, {}
    verdicts, dll = {}, None
    for line in open(reports[-1], encoding="utf-8"):
        m = re.match(r"- (\w+): installed build is", line)
        if m:
            dll = m.group(1)
        elif dll and "tracked addresses" in line:
            verdicts[dll] = line.strip(" -\n")
            dll = None
    return os.path.basename(reports[-1]), verdicts


def citations():
    """Every src/ line that names an address, keyed by the address."""
    found = {}
    pattern = re.compile(r"(?:FUN_|0x)?(1[0-9a-f]{8})\b", re.I)
    for path in glob.glob(os.path.join(REPO, "src", "**", "*.cs"), recursive=True):
        rel = os.path.relpath(path, REPO).replace("\\", "/")
        with open(path, encoding="utf-8", errors="replace") as f:
            for n, line in enumerate(f, 1):
                for m in pattern.finditer(line):
                    found.setdefault(m.group(1).lower(), []).append(f"{rel}:{n}")
    return found


def main(out):
    cited = citations()
    report, verdicts = patch_verdicts()
    lists = sorted(glob.glob(os.path.join(NAMES, "*.manual.json")))
    lines = [
        "# Addresses",
        "",
        "Every function and data address the port relies on, per DLL build.",
        "Generated by `tools/re/address_doc.py` from `tools/re/names/make_manual.py`,",
        "which is the one place addresses are kept: add them there, run it, then run",
        "this. `tools/re/apply_names.py` writes the names into the Ghidra project,",
        "and `tools/re/patch_check.py` finds every one again after a CS2 update",
        "(identical, relocated, moved, changed or missing), so this list is how a",
        "port is kept honest across patches.",
        "",
        "All the DLLs load at 0x180000000, so an address means nothing without its",
        "build: each section names the file it was read from. \"Installed\" says",
        "whether the game on this machine still ships that exact build.",
        "",
        "Names are ours unless they carry a class (`CMapCable::vf217` is an RTTI",
        "slot, `CVoxelSampler3::MergeClusterSet` an assert string). The harvested",
        "names (asserts, RTTI, log strings; tens of thousands per DLL) are in",
        "`tools/re/names/<dll>_<build>.json`, not here.",
        "",
    ]
    total = 0
    for path in lists:
        stem = os.path.basename(path)[: -len(".manual.json")]
        dll, build = stem.rsplit("_", 1)
        rows = json.load(open(path, encoding="utf-8"))["functions"]
        total += len(rows)
        lines.append(f"## {dll}.dll, build {build}")
        lines.append("")
        source = build_file(dll, build)
        if source:
            digest = sha256(source)
            installed = INSTALLED.get(dll, os.path.join(CS2, "game", "bin", "win64", dll + ".dll"))
            same = os.path.exists(installed) and sha256(installed) == digest
            lines.append(f"- file: `{os.path.basename(source)}`, {os.path.getsize(source):,} bytes, PE time {pe_time(source)}")
            lines.append(f"- SHA-256 `{digest}`")
            lines.append(f"- installed: {'this build' if same else 'a different build'}")
            if dll in verdicts:
                lines.append(f"- against the installed build ({report}): {verdicts[dll]}")
        else:
            lines.append("- file: not found locally")
        lines.append(f"- {len(rows)} addresses")
        lines.append("")
        by_module = {}
        for r in rows:
            by_module.setdefault(r.get("module") or "(untagged)", []).append(r)
        for module in sorted(by_module):
            lines.append(f"### {module}")
            lines.append("")
            lines.append("| address | name | what | cited in |")
            lines.append("|---|---|---|---|")
            for r in sorted(by_module[module], key=lambda r: int(r["addr"], 16)):
                where = cited.get(r["addr"].lower(), [])
                shown = ", ".join(f"`{w}`" for w in where[:3]) + (f" +{len(where) - 3}" if len(where) > 3 else "")
                note = (r.get("note") or "").replace("|", "\\|")
                lines.append(f"| `{r['addr']}` | `{r['name']}` | {note} | {shown} |")
            lines.append("")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{total} addresses over {len(lists)} builds -> {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, "docs", "ADDRESSES.md"))
